[multiformat]
description = 'https://multiformats.io/'

[multiaddr]
description = 'https://multiformats.io/multiaddr/'
valid = [
    '/ip4/127.0.0.1/udp/9090/quic',
    '/ip6/::1/tcp/3217',
    '/ip4/127.0.0.1/tcp/80/http/baz.jpg',
    '/dns4/foo.com/tcp/80/http/bar/baz.jpg',
    '/dns6/foo.com/tcp/443/https'
]

[multihash]
description = 'https://multiformats.io/multihash/'
valid = ['11148a173fd3e32c0fa78b90fe42d305f202244e2739', '122041dd7b6443542e75701aa98a0c235951a28a0d851b11564d20022ab11d2589a8']
fallback = 'text-line'

[multicodec]
description = 'https://github.com/multiformats/multicodec'
fallback = 'text-line'

[ipfs-cid]
description = 'https://docs.ipfs.io/guides/concepts/cid/'
fallback = 'text-line'

[libp2p-peerid]
description = 'https://docs.libp2p.io/concepts/peer-id/'
fallback = 'text-line'
