[impp]
description = 'A URL for an instant messaging protocol endpoint, such as "xmpp:username@example.net".'

[uuid]
description = 'A universally unique identifier (UUID) is a 128-bit label used for information in computer systems. The term globally unique identifier (GUID) is also used.'