[socket-addr]
description = 'An internet socket address, either IPv4 or IPv6.'

valid = [
    '[2001:db8:85a3:8d3:1319:8a2e:370:7348]:443',
    '[::1]:8080',
    '127.0.0.1:8080',
    '0.0.0.0:8080'
]

invalid = [
    '127.0.0.1',
    'localhost:80',
    '127.0.0.1:8080, [::1]:8080',
    ''
]

[socket-addr.type]
html = 'text'
json = { type = 'string' }
rust = 'std::net::SocketAddr'



[socket-addr-v4]
description = 'IPv4 socket addresses consist of an IPv4 address and a 16-bit port number, as stated in IETF RFC 793.'

[socket-addr-v6]
description = 'IPv6 socket addresses consist of an IPv6 address, a 16-bit port number, as well as fields containing the traffic class, the flow label, and a scope identifier (see IETF RFC 2553, Section 3.3 for more details).'

[socket-addrs]
# pattern = '^[-a-z0-9\.]+(?:(?:\d+))?$'
description = 'An collection of internet socket address, either IPv4 or IPv6.'
valid = [
    # this is multiple socket addresses
    ['localhost:80'],
    ['[2001:db8:85a3:8d3:1319:8a2e:370:7348]:443'],
    ['[::1]:8080'],
    ['127.0.0.1:8080'],
    ['127.0.0.1:8080', '[::1]:8080']
]

invalid = [
    ['127.0.0.1'],
    ['localhost']
]

[socket-addrs.type]
html = 'text'
json = { type = 'array', items = { type = 'string' } }
rust = 'impl std::iter::Iterator<Item = std::net::SocketAddr>'

[ipv4-addr]
description = 'IPv4 addresses are defined as 32-bit integers in IETF RFC 791. They are usually represented as four octets.'
pattern = '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'

[ipv4-addr.valid]
'8.8.8.8' = 'google dns'
'0.0.0.0' = 'broadcast'

[ipv4-addr.type]
html = 'text'
json = { type = 'string' }
rust = 'std::net::Ipv4Addr'

[ipv6-addr]
description = 'IPv6 addresses are defined as 128-bit integers in IETF RFC 4291. They are usually represented as eight 16-bit segments.'
pattern = '^(?:(?:[0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,7}:|(?:[0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,5}(?::[0-9a-fA-F]{1,4}){1,2}|(?:[0-9a-fA-F]{1,4}:){1,4}(?::[0-9a-fA-F]{1,4}){1,3}|(?:[0-9a-fA-F]{1,4}:){1,3}(?::[0-9a-fA-F]{1,4}){1,4}|(?:[0-9a-fA-F]{1,4}:){1,2}(?::[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:(?:(?::[0-9a-fA-F]{1,4}){1,6})|:(?:(?::[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(?::[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(?:ffff(?::0{1,4}){0,1}:){0,1}(?:(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])|(?:[0-9a-fA-F]{1,4}:){1,4}:(?:(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$'

[ipv6-addr.type]
html = 'text'
json = { type = 'string' }
rust = 'std::net::Ipv6Addr'

# https://medium.com/@choudharyarpit99/leetcode-468-validate-ip-address-b72c028df6c6
[ipv6-addr.valid]
'::1' = 'IPv6 loopback'
'::ffff:127.0.0.1' = 'IPv4 loopback'
'a:b:c:d:e:f:g:h' = 'simple'
'2001:0db8:85a3:0000:0000:8a2e:0370:7334' = 'full eight groups of four hexadecimal digits'
'2001:db8:85a3:0:0:8A2E:0370:7334' = 'Omit leading zeros and using upper cases'

[ipv6-addr.invalid]
'127.0.0.1' = 'ipv4'
'2001:0db8:85a3::8A2E:0370:7334' = 'replace a consecutive group of zero value with a single empty group using two consecutive colons (::)'
'02001:0db8:85a3:0000:0000:8a2e:0370:7334' = 'extra leading zeros'

[dns-hostname]
type = 'text'
pattern = '^([a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]\.){1,127}[A-Za-z]{2,63}$'

valid = ['google', 'localhost']
invalid = ['','nope.-.tld', 'toooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo.long']

[dns-label]
maxlength = 63
pattern = '^[a-z][a-z0-9\-]*[a-z0-9]$'
