[charset]
description = 'https://developer.mozilla.org/en-US/docs/Glossary/character_encoding'
# https://docs.rs/encoding_rs/latest/encoding_rs/index.html
valid = [
    # default
    'UTF-8',
    # Besides UTF-8, the following encodings are explicitly listed in the HTML standard itself, with reference to the Encoding Standard:
    'ISO-8859-2',
    'ISO-8859-7',
    'ISO-8859-8',
    'Windows-874',
    'Windows-1250',
    'Windows-1251',
    'Windows-1252',
    'Windows-1254',
    'Windows-1255',
    'Windows-1256',
    'Windows-1257',
    'Windows-1258',
    'GB18030',
    'Big5',
    'Shift JIS',
    'ISO-2022-JP',
    'EUC-KR',
    'UTF-16BE',
    'UTF-16LE',
    # The following additional encodings are listed in the Encoding Standard, and support for them is therefore also required:
    'Code page 866',
    'ISO-8859-3',
    'ISO-8859-4',
    'ISO-8859-5',
    'ISO-8859-6',
    'ISO-8859-8-I',
    'ISO-8859-10',
    'ISO-8859-13',
    'ISO-8859-14',
    'ISO-8859-15',
    'ISO-8859-16',
    'KOI8-R',
    'KOI8-U',
    'KOI8-RU',
    'Mac OS Roman',
    'Windows-1253',
    'Mac OS Cyrillic',
    'GBK',
    'EUC-JP',
]

invalid = [
    # The following encodings are listed as explicit examples of forbidden encodings:
    'CESU-8',
    'UTF-7',
    'BOCU-1',
    'SCSU',
    'EBCDIC',
    'UTF-32',
    # replacement
    'ISO-2022-KR',
    'ISO-2022-CN',
    'ISO-2022-CN-EXT',
    'HZ-GB-2312',
]

[http-content-type]
description = 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type'
fields = { media-type = 'mime', charset = 'charset', boundary = 'string'}
valid = ['text/html; charset=UTF-8', 'multipart/form-data; boundary=something']

[media-type]
valid = ['text/plain;charset=UTF-8', 'image/svg+xml', 'model/vrml']